### ISSUE TITLE
Error: Spawn scene object not found for x

### ISSUE THREAD

**Issue by bilke** [widVE/UniCAVE#13]
I am trying out UniCAVE (and am very excited about it! thanks!) but I get the following error when entering playmode:

```
Spawn scene object not found for x
UnityEngine.Networking.NetworkCallbacks:LateUpdate() (at Library/PackageCache/com.unity.multiplayer-hlapi@1.0.4/Runtime/NetworkCallbacks.cs:11)
```

It is coming for every `NetworkIdentity`-component in the scene.

I do not know if this is also the reason that I get no VRPN inputs.

- Unity 2019.3.11
- https://github.com/widVE/UniCAVE/commit/ebea488ec797ec08551b1856f186e0581fa9927b
- Platform: Windows 10 (the error is the same on macOS 10.15)
- I tested both the UniCAVE repo standalone as well as in an own repo with UniCAVE installed via the package manager (local package on disk)

Do you have an idea what I can try? Thanks a lot!

**Comment by neurograph** [comment]
Hi, were you able to solve this?

**Comment by bilke** [comment]
@neurograph No but I found out that the VRPN inputs work when running the built executable.
